### ISSUE TITLE
Tutorials 4 and 5 minor edits

### ISSUE THREAD

**Issue by dcol2804** [traitecoevo/traits.build-book#8]
Tutorial 4: I'm not sure how essential this is but should there be a line reminding the user to add in the description, basis_of_record, life_stage and sampling_strategy from the.txt file? And to add the location details as per tutorial 3 (creating a location column and adding coordinates from sampling strategy text?).  If sampling_strategy text from the .txt file is pasted in, the degree symbol on the text also creates an error when I tested the dataset - I converted this text to decimal degrees using an online converter.. not sure if this was the best way to do this? 

Tutorial 5: Extremely minor, but I did wonder what the date2 column in the data was for when I assigned the date column.

**Comment by dfalster** [comment]
@ehwenk  for you

**Comment by ehwenk** [comment]
I've fixed the degree signs (replacing with the word "deg" under sampling strategy, but the intent for adding location in Tutorial 4 was to add latitude/longitude directly from the data file using the code provided, rather than manually - https://traitecoevo.github.io/traits.build-book/tutorial_dataset_4.html#location_names.
